server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${DOCKER_HOST:localhost}

  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0